# Generated by Django 4.2.7 on 2024-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_category_options_product_sale_prisce_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sale_prisce',
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
    ]
