# Generated by Django 5.0.2 on 2024-05-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_webbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='webbanner',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
    ]
