# Generated by Django 5.0.2 on 2024-05-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_productimage_delete_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.FileField(upload_to='uploads/products/'),
        ),
    ]
