# Generated by Django 5.0.2 on 2024-05-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.ManyToManyField(blank=True, to='store.specification'),
        ),
    ]
