# Generated by Django 5.0.2 on 2024-05-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_product_specifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specifications',
            new_name='specification',
        ),
    ]
