# Generated by Django 5.0.2 on 2024-05-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_rename_specifications_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default=1, to='store.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.ManyToManyField(blank=True, default=1, null=True, to='store.specification'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='specification',
            name='value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
