# Generated by Django 5.0.2 on 2024-03-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_new_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new_product',
        ),
    ]
