# Generated by Django 5.0.6 on 2024-05-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productimage_product_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_images',
            field=models.ImageField(null=True, upload_to='uploads/products'),
        ),
    ]
