# Generated by Django 5.0.1 on 2024-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
