# Generated by Django 5.0.1 on 2024-02-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_percentage_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percentage_discount',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True),
        ),
    ]
